---
title: "Gov 50 Final Project"
author: Ariana Smartt
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to how religious views impact policy preferences. I'm wondering how religiosity and opinions about issues like government welfare interact. I'm also wondering how religiosity impacts party attachment. The data I'm interested in is ANES survey questions from 1956-2020. This data allows me to look at trends in voting patterns and religiosity over time. 

## Data

Does more church attendance lead to more good acts? In this study, I plan to examine the relationship between frequency of worship and acts of kindness. I hypothesize that the more one attends church, the more good acts they will report to have done in the last 12 months. I project this because I think that more exposure to messages of generosity and self-sacrifice would lead to more charitable behavior. The sample I’ll be using to investigate this is a 2001 survey of nearly 60,000 church attenders across all the major denominations. My unit of analysis is an attender. The explanatory variable of interest is their church attendance. The variable is coded from 1 to 7, 1 being not often to 7 being more than once a week. My outcome variable is whether they report doing good deeds. The variable is coded =1 for checked and =0 for unchecked. If I observe more good deeds when attendance is higher, this would provide support for my hypothesis. If, on the other hand, I observe fewer good deeds among those with higher attendance, this would provide evidence against my hypothesis. When I run my regression of the amount of good deeds related to church attendance, a positive, significant coefficient would indicate support for my hypothesis.